### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by oouo-diogo-perdigao** [asurance/vscode-sound-player#2]
Thanks for this extension.
I am brazilian but it would be really cool if you put an option for the text to appear in english. The language in Chinese is very different from the Latin alphabet. English becomes universal.

**Comment by asurance** [comment]
I just published a new version. In this version, text are replaced by icons so that it looks more like a sound player. Meanwhile, I don't need to support other languages. 😊

**Comment by oouo-diogo-perdigao** [comment]
Perfect,
